//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krupagallarydbEntities : DbContext
    {
        public krupagallarydbEntities()
            : base("name=krupagallarydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_AdminRoles> Tbl_AdminRoles { get; set; }
        public DbSet<Tbl_AdminUsers> Tbl_AdminUsers { get; set; }
        public DbSet<Tbl_Categories> Tbl_Categories { get; set; }
        public DbSet<Tbl_ClientOtherDetails> Tbl_ClientOtherDetails { get; set; }
        public DbSet<Tbl_ClientRoles> Tbl_ClientRoles { get; set; }
        public DbSet<Tbl_ClientUsers> Tbl_ClientUsers { get; set; }
        public DbSet<Tbl_ItemStocks> Tbl_ItemStocks { get; set; }
        public DbSet<Tbl_Offers> Tbl_Offers { get; set; }
        public DbSet<Tbl_OrderItemDetails> Tbl_OrderItemDetails { get; set; }
        public DbSet<Tbl_Orders> Tbl_Orders { get; set; }
        public DbSet<Tbl_ProductItemImages> Tbl_ProductItemImages { get; set; }
        public DbSet<Tbl_ProductItems> Tbl_ProductItems { get; set; }
        public DbSet<Tbl_Products> Tbl_Products { get; set; }
        public DbSet<Tbl_SubProducts> Tbl_SubProducts { get; set; }
    }
}
