//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krupagallarydbEntities : DbContext
    {
        public krupagallarydbEntities()
            : base("name=krupagallarydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_AdminRoles> tbl_AdminRoles { get; set; }
        public DbSet<tbl_AdminUsers> tbl_AdminUsers { get; set; }
        public DbSet<tbl_Categories> tbl_Categories { get; set; }
        public DbSet<tbl_ClientOtherDetails> tbl_ClientOtherDetails { get; set; }
        public DbSet<tbl_ClientRoles> tbl_ClientRoles { get; set; }
        public DbSet<tbl_ClientUsers> tbl_ClientUsers { get; set; }
        public DbSet<tbl_ItemStocks> tbl_ItemStocks { get; set; }
        public DbSet<tbl_Offers> tbl_Offers { get; set; }
        public DbSet<tbl_OrderItemDetails> tbl_OrderItemDetails { get; set; }
        public DbSet<tbl_Orders> tbl_Orders { get; set; }
        public DbSet<tbl_ProductItemImages> tbl_ProductItemImages { get; set; }
        public DbSet<tbl_ProductItems> tbl_ProductItems { get; set; }
        public DbSet<tbl_Products> tbl_Products { get; set; }
        public DbSet<tbl_SubProducts> tbl_SubProducts { get; set; }
        public DbSet<tbl_ContactFormData> tbl_ContactFormData { get; set; }
        public DbSet<tbl_DistributorRequestDetails> tbl_DistributorRequestDetails { get; set; }
    }
}
