//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orders
    {
        public long OrderId { get; set; }
        public long ClientUserId { get; set; }
        public decimal OrderAmount { get; set; }
        public string OrderShipCity { get; set; }
        public string OrderShipState { get; set; }
        public string OrderShipAddress { get; set; }
        public string OrderShipPincode { get; set; }
        public string OrderShipClientName { get; set; }
        public string OrderShipClientPhone { get; set; }
        public long OrderStatusId { get; set; }
        public string PaymentType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public string RazorpayOrderId { get; set; }
        public string RazorpayPaymentId { get; set; }
        public string RazorSignature { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
        public Nullable<int> ShippingStatus { get; set; }
        public Nullable<decimal> PointsUsed { get; set; }
        public Nullable<long> InvoiceNo { get; set; }
        public string InvoiceYear { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<decimal> CreditAmountUsed { get; set; }
        public Nullable<decimal> WalletAmountUsed { get; set; }
        public Nullable<decimal> AmountByRazorPay { get; set; }
        public Nullable<bool> IsCashOnDelivery { get; set; }
        public Nullable<decimal> CreditAmountRefund { get; set; }
        public Nullable<decimal> WalletAmountRefund { get; set; }
        public Nullable<decimal> OnlinePaymentAmtRefund { get; set; }
        public Nullable<decimal> ExtraAmount { get; set; }
        public Nullable<bool> IsExtraAmountReceived { get; set; }
        public Nullable<decimal> AdvancePaymentRecieved { get; set; }
        public string GSTNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> HasFreeItems { get; set; }
    }
}
