//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderItemDetails
    {
        public long OrderDetailId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> ProductItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Sku { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GSTPer { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<decimal> FinalItemPrice { get; set; }
    }
}
