//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdminRoleModules
    {
        public tbl_AdminRoleModules()
        {
            this.tbl_AdminRolePermissions = new HashSet<tbl_AdminRolePermissions>();
        }
    
        public int AdminRoleModuleId { get; set; }
        public string ModuleName { get; set; }
        public int DisplayOrder { get; set; }
        public bool None { get; set; }
        public bool View { get; set; }
        public bool Add { get; set; }
        public bool Edit { get; set; }
        public bool Full { get; set; }
    
        public virtual ICollection<tbl_AdminRolePermissions> tbl_AdminRolePermissions { get; set; }
    }
}
