//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StockReport
    {
        public long Pk_StockReport_Id { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
