//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Feedbacks
    {
        public long FeedbackId { get; set; }
        public string AboutService { get; set; }
        public string AboutDeliveryBoyService { get; set; }
        public string AboutDeliveryBoyBehaviour { get; set; }
        public string OurQuality { get; set; }
        public string Suggestion { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<long> ClientUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> FeedbackOfMonth { get; set; }
    }
}
