//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemReturnCancelReplace
    {
        public long ItemReturnCancelReplaceId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> ClientUserId { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> VariantItemId { get; set; }
    }
}
