//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChatRoomUsers
    {
        public long ChatRoomUserId { get; set; }
        public Nullable<long> Fk_ChatRoomId { get; set; }
        public Nullable<long> Fk_UserId { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
