//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FreeOffers
    {
        public long FreeOfferId { get; set; }
        public Nullable<decimal> OrderAmountFrom { get; set; }
        public Nullable<decimal> OrderAmountTo { get; set; }
        public Nullable<System.DateTime> OfferStartDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
