//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentTransaction
    {
        public long PK_PaymentTransactionId { get; set; }
        public bool IsCredit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long OrderId { get; set; }
        public Nullable<long> OrderItemId { get; set; }
        public string Remarks { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<long> TransactionBy { get; set; }
        public bool IsAdmin { get; set; }
    }
}
