//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClientOtherDetails
    {
        public long ClientOtherDetailsId { get; set; }
        public long ClientUserId { get; set; }
        public string Addharcardno { get; set; }
        public string Pancardno { get; set; }
        public string GSTno { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipAddress { get; set; }
        public Nullable<decimal> CreditLimitAmt { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ShipFirstName { get; set; }
        public string ShipLastName { get; set; }
        public string ShipPhoneNumber { get; set; }
        public string ShipEmail { get; set; }
        public string ShipPostalcode { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string ShopPhoto { get; set; }
        public string ShopName { get; set; }
        public string PanCardPhoto { get; set; }
        public string GSTPhoto { get; set; }
        public string DistributorCode { get; set; }
        public string AddharPhoto { get; set; }
        public string ShipGSTNo { get; set; }
        public string AddharPhoto2 { get; set; }
        public string ShopPhoto2 { get; set; }
    }
}
