//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DealerTerms
    {
        public long Pk_DealerTerms_Id { get; set; }
        public Nullable<long> Fk_Dealer_Id { get; set; }
        public string Terms { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> TermsType { get; set; }
        public string TermsTitle { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
