//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemAvailablePincode
    {
        public long ItemAvailablePincodeId { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<long> ProductItemId { get; set; }
    }
}
