//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemReplace
    {
        public long ItemReplaceId { get; set; }
        public Nullable<long> ItemDetailId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<System.DateTime> ReplaceDate { get; set; }
        public Nullable<long> AssignPersonId { get; set; }
    }
}
