//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FreeOfferItems
    {
        public long FreeofferItemId { get; set; }
        public Nullable<long> FreeOfferId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> SubProductId { get; set; }
        public Nullable<long> ProductItemId { get; set; }
        public Nullable<long> VariantItemId { get; set; }
        public long Qty { get; set; }
    }
}
