//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseItems
    {
        public long PurchaseItemId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> SubProductId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> VariantId { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<decimal> LabourCharge { get; set; }
        public Nullable<decimal> ExtraPlusMinus { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TradeDiscount { get; set; }
        public Nullable<decimal> CashDiscount { get; set; }
        public Nullable<decimal> ExtraPlusMinus2 { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<long> StockVariantId { get; set; }
        public Nullable<long> StockId { get; set; }
        public Nullable<long> StockReportId { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public long Fk_PurchaseId { get; set; }
    }
}
