//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactFormData
    {
        public long ContactForm_Id { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FromWhere { get; set; }
        public Nullable<long> ClientUserId { get; set; }
        public System.DateTime MessageDate { get; set; }
        public bool IsDelete { get; set; }
    }
}
