//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BidDealers
    {
        public long Pk_BidDealers { get; set; }
        public Nullable<long> Fk_BidId { get; set; }
        public Nullable<long> FK_DealerId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> MinimumQtyToBuy { get; set; }
        public string TermsAndCondions { get; set; }
        public string PaymentTerms { get; set; }
        public string PaymentType { get; set; }
        public string PickupCity { get; set; }
        public string PickupCityPincode { get; set; }
        public Nullable<int> BidValidDays { get; set; }
        public Nullable<System.DateTime> BidSendDate { get; set; }
        public Nullable<System.DateTime> BidModifiedDate { get; set; }
        public Nullable<int> BidStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Fk_Item_Id { get; set; }
        public string RejectReason { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string BidPhoto { get; set; }
        public string BidPhoto2 { get; set; }
        public string BidPhoto3 { get; set; }
    }
}
