//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProductItems
    {
        public long Pk_ProductItem_Id { get; set; }
        public Nullable<long> Fk_SubProductId { get; set; }
        public Nullable<long> Fk_ProductId { get; set; }
        public Nullable<long> Fk_CategoryId { get; set; }
        public string ProductItemName { get; set; }
        public Nullable<decimal> MRPPrice { get; set; }
        public Nullable<decimal> DistributorPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public string MainImage { get; set; }
        public string Notification { get; set; }
        public string Sku { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ItemDescription { get; set; }
    }
}
