//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentHistory
    {
        public long PaymentHistory_Id { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal AmountDue { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public long OrderId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PaymentBy { get; set; }
    }
}
