//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ComboOfferSubItems
    {
        public long ComboOfferSubItemId { get; set; }
        public long CategoryId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> SubProductId { get; set; }
        public long ProductItemId { get; set; }
        public long VariantItemId { get; set; }
        public long Qty { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public Nullable<long> ComboOfferId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
