//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderItemDelivery
    {
        public long OrderItemDeliveryId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> OrderItemId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> DelieveryPersonId { get; set; }
        public Nullable<long> AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<decimal> AmountToReceived { get; set; }
        public Nullable<bool> IsAmountReceived { get; set; }
    }
}
