//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSContent
    {
        public int SMSContentId { get; set; }
        public string SMSTitle { get; set; }
        public string SMSDescription { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
