//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DistributorRequestDetails
    {
        public long DistributorRequestId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string AddharcardNo { get; set; }
        public string PanCardNo { get; set; }
        public string GSTNo { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string AlternateMobileNo { get; set; }
        public string Prefix { get; set; }
        public string ShopName { get; set; }
        public string ShopPhoto { get; set; }
        public string PanCardPhoto { get; set; }
        public string GSTPhoto { get; set; }
        public string AddharPhoto { get; set; }
        public string ProfilePhoto { get; set; }
    }
}
