//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchasePayment
    {
        public long PurchasePaymentId { get; set; }
        public Nullable<long> PurchaseId { get; set; }
        public Nullable<long> DealerId { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentBy { get; set; }
        public Nullable<decimal> Vatav { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModfiedBy { get; set; }
        public string Remarks { get; set; }
        public string ChequeBankName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
