//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReviewRating
    {
        public long ReviewRatingId { get; set; }
        public Nullable<long> ProductItemId { get; set; }
        public Nullable<long> OrderDetailId { get; set; }
        public Nullable<long> ClientUserId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
