//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrupaBuildGallery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ComboOfferMaster
    {
        public long ComboOfferId { get; set; }
        public long MainItemCatId { get; set; }
        public Nullable<long> MainItemsSubProductId { get; set; }
        public Nullable<long> MainItemProductId { get; set; }
        public long MainItemId { get; set; }
        public long MainItemVarintId { get; set; }
        public long MainItemQty { get; set; }
        public string OfferTitle { get; set; }
        public decimal OfferPrice { get; set; }
        public System.DateTime OfferStartDate { get; set; }
        public System.DateTime OfferEndDate { get; set; }
        public string OfferImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> TotalActualPrice { get; set; }
        public Nullable<decimal> MainItemActualPrice { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsCashOnDelivery { get; set; }
    }
}
